CREATE TABLE houblon (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL UNIQUE,
    variete TEXT,
    date_debut DATE,
    date_fin DATE,
    commentaire TEXT,
    sexe TEXT
);

CREATE TABLE position (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    houblon_id INTEGER NOT NULL,
    localite TEXT,
    site_naturel INTEGER NOT NULL DEFAULT 1,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT fk_position_houblon
        FOREIGN KEY (houblon_id) REFERENCES houblon(id)
);

CREATE TABLE suivi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    houblon_id INTEGER NOT NULL,
    date_observation DATE NOT NULL,
    hauteur_cm INTEGER,
    etat_sanitaire TEXT,
    commentaire TEXT,
    CONSTRAINT fk_suivi_houblon
        FOREIGN KEY (houblon_id) REFERENCES houblon(id)
);

CREATE TABLE traitement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    houblon_id INTEGER NOT NULL,
    date_traitement DATE,
    produit TEXT,
    dose TEXT,
    commentaire TEXT,
    CONSTRAINT fk_traitement_houblon
        FOREIGN KEY (houblon_id) REFERENCES houblon(id)
);

CREATE TABLE recolte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    houblon_id INTEGER NOT NULL,
    date_recolte DATE,
    poids_frais DOUBLE PRECISION,
    poids_sec DOUBLE PRECISION,
    commentaire TEXT,
    CONSTRAINT fk_recolte_houblon
        FOREIGN KEY (houblon_id) REFERENCES houblon(id)
);

CREATE TABLE particularite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    houblon_id INTEGER NOT NULL,
    particularite TEXT,
    commentaire TEXT,
    CONSTRAINT fk_particularite_houblon
        FOREIGN KEY (houblon_id) REFERENCES houblon(id)
);

CREATE TABLE relations (
    male_id INTEGER,
    femelle_id INTEGER,
    distance_km DOUBLE PRECISION
);
