name: Project status

on:
  push:

permissions:
  contents: read

jobs:
  project-info:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le Project
        env:
          GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: |
          gh api graphql \
            -f query='
              query {
                user(login: "DimitriGerson") {
                  projectV2(number: 11) {
                    id
                    number
                    title
                  }
                }
              }
            '
